-- Gera��o de Modelo f�sico
-- Sql ANSI 2003 - brModelo.

CREATE DATABASE jairneto_bolanarede;

USE jairneto_bolanarede;

CREATE TABLE TIPO_FALTA (
ID_TIPO_FALTA int(4) PRIMARY KEY auto_increment,
CARTAO varchar(10) not null
);

CREATE TABLE SELECAO (
ID_SELECAO int(4) PRIMARY KEY auto_increment,
NOME varchar(40) not null,
DATA_CRIACAO datetime not null default now(),
COR_CAMISA_1 varchar(20) not null,
COR_CAMISA_2 varchar(20),
COR_CAMISA_3 varchar(20)
);

CREATE TABLE CAMPEONATO (
ID_CAMPEONATO int(4) PRIMARY KEY auto_increment,
NOME varchar(20) not null
);

CREATE TABLE COLOCACAO (
ID_COLOCACAO int(4) PRIMARY KEY auto_increment,
COLOCACAO int(2) not null,
ID_SELECAO int(4) not null,
ID_CAMPEONATO int(4) not null,
FOREIGN KEY(ID_SELECAO) REFERENCES SELECAO (ID_SELECAO),
FOREIGN KEY(ID_CAMPEONATO) REFERENCES CAMPEONATO (ID_CAMPEONATO)
);

CREATE TABLE SELECAO_CAMPEONATO (
ID_SELECAO_CAMPEONATO int(4) PRIMARY KEY auto_increment,
ID_CAMPEONATO int(4) not null,
ID_SELECAO int(4) not null,
FOREIGN KEY(ID_CAMPEONATO) REFERENCES CAMPEONATO (ID_CAMPEONATO),
FOREIGN KEY(ID_SELECAO) REFERENCES SELECAO (ID_SELECAO)
);

CREATE TABLE JOGO (
ID_JOGO int(4) PRIMARY KEY auto_increment,
DATATIME datetime not null default now(),
TERMINADO boolean,
VENCEDOR int(4),
ID_SELECAO_1 int(4) not null,
ID_SELECAO_2 int(4) not null,
ID_CAMPEONATO int(4),
FOREIGN KEY(VENCEDOR) REFERENCES SELECAO (ID_SELECAO),
FOREIGN KEY(ID_SELECAO_1) REFERENCES SELECAO (ID_SELECAO),
FOREIGN KEY(ID_SELECAO_2) REFERENCES SELECAO (ID_SELECAO),
FOREIGN KEY(ID_CAMPEONATO) REFERENCES CAMPEONATO (ID_CAMPEONATO)
);

CREATE TABLE GOL (
ID_GOL int(4) PRIMARY KEY auto_increment,
TEMPO int(1) not null,
CRONOMETRO datetime not null default now(),
NUMERO_CAMISA int(2) not null,
ID_SELECAO int(4) not null,
ID_SELECAO_MARCADOR int(4) not null,
ID_JOGO int(4) not null,
FOREIGN KEY(ID_SELECAO) REFERENCES SELECAO (ID_SELECAO),
FOREIGN KEY(ID_SELECAO_MARCADOR) REFERENCES SELECAO (ID_SELECAO),
FOREIGN KEY(ID_JOGO) REFERENCES JOGO (ID_JOGO)
);

CREATE TABLE FALTA (
ID_FALTA int(4) PRIMARY KEY auto_increment,
NUMERO_CAMISA int(2) not null,
ID_JOGO int(4) not null,
ID_TIPO_FALTA int(4) not null,
ID_SELECAO int(4) not null,
FOREIGN KEY(ID_JOGO) REFERENCES JOGO (ID_JOGO),
FOREIGN KEY(ID_TIPO_FALTA) REFERENCES TIPO_FALTA (ID_TIPO_FALTA),
FOREIGN KEY(ID_SELECAO) REFERENCES SELECAO (ID_SELECAO)
);